// vue/src/App.vue
<script setup lang="ts">
import {ref} from 'vue';
import todoStore,{type Task} from './todoStore';

const {state,addTask,checkTask,uncheckTask,deleteTask} = todoStore;

const titleInputRef = ref<HTMLInputElement | null>(null);

const _handleSubmitTask = (e: Event) => {
  e.preventDefault();
  if (titleInputRef.value) {
    addTask(titleInputRef.value.value);
    titleInputRef.value.value = '';
  }
};

const _handleToggleTask = (task: Task) => {
  if (task.done) {
    uncheckTask(task.id);
  } else {
    checkTask(task.id);
  }
};

const _handleDeleteTask = (task: Task) => {
  deleteTask(task.id);
};

</script>

<template>
  <h1>✨ TODO App ✨</h1>
  <form class="todo-form" @submit="_handleSubmitTask">
    <input type="text" ref="titleInputRef" name="title" />
    <button type="submit">Add</button>
  </form>
  <ul className="todo-list">
    <li v-for="task in state.tasks" :key="task.id">
      <input type="checkbox" v-model="task.done" @click="_handleToggleTask(task)" />
      <span class="title">{{ task.title }}</span>
      <button @click="_handleDeleteTask(task)">Delete</button>
    </li>
  </ul>
</template>

<style scoped>
#root {
  max-width: 1280px;
  margin: 0 auto;
  padding: 2rem;
  text-align: center;
}

input {
  border: 1px solid #ccc;
  border-radius: 4px;
  padding: 0.5rem 1rem;
  font-size: 1rem;
  margin-right: 1rem;
}

.todo-list {
  list-style-type: none;
  padding: 0;
}

.todo-list li {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0.5rem 1rem;
}

.todo-list li .title {
  flex: 1;
  text-align: left;
}
</style>

// react/src/App.tsx
import {FunctionComponent, useReducer, useRef} from 'react';
import './App.css';
import {Task, TodoActionTypes, todoReducer} from './todoReducer';

export const App: FunctionComponent = () => {
    const [state, dispatch] = useReducer(todoReducer, {tasks: []});
    const titleInputRef = useRef<HTMLInputElement>(null);

    const _handleSubmitTask = (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        const input = titleInputRef.current;

        if (!input) {
            return;
        }

        dispatch({type: TodoActionTypes.ADD_TASK, payload: {title: input.value}});
        input.value = '';
    };

    const _handleToggleTask = (task: Task) => {
        dispatch({
            type: task.done ? TodoActionTypes.UNCHECK_TASK : TodoActionTypes.CHECK_TASK,
            payload: {id: task.id},
        });
    };

    const _handleDeleteTask = (task: Task) => {
        dispatch({type: TodoActionTypes.DELETE_TASK, payload: {id: task.id}});
    };

    return (
        <>
            <h1>✨ TODO App ✨</h1>
            <form className="todo-form" onSubmit={_handleSubmitTask}>
                <input type="text" ref={titleInputRef} name="title" />
                <button type="submit">Add</button>
            </form>
            <ul className="todo-list">
                {state.tasks.map((task) => (
                    <li key={task.id}>
                        <input type="checkbox" checked={task.done} onChange={() => _handleToggleTask(task)} />
                        <span className="title">{task.title}</span>
                        <button onClick={() => _handleDeleteTask(task)}>Delete</button>
                    </li>
                ))}
            </ul>
        </>
    );
};
